from decouple import config

ACCOUNT_ID_LENGTH = 8

DB_ENCRYPTION_KEY = config('DB_ENCRYPTION_KEY')
ACCOUNTS_TABLE = config('ACCOUNTS_TABLE')
CONFIG_FILE = config('CONFIG_FILE')
DYNAMODB_HOST = config('DYNAMODB_HOST')
DEVICE_NAME = config('DEVICE_NAME')
PUSH_TOKEN = config('PUSH_TOKEN')
